CREATE TYPE [dbo].[FRMLoad] AS TABLE
( 
     [Location ID] nvarchar(max),[1 mile pop] nvarchar(max), 
     [3 mile pop] nvarchar(max),[5 mile pop] nvarchar(max), 
     [Actual Opening] nvarchar(max),[AverageTerm] nvarchar(max), 
     [Avg  monthly gross personal training revenue] nvarchar(max), 
     [BOE Verified] nvarchar(max),[Close Date] nvarchar(max), 
     [Competition] nvarchar(max),[E-mail Address] nvarchar(max), 
     [Exchange Rate] nvarchar(max),[Existing Sales Rep] nvarchar(max), 
     [Express Location] nvarchar(max),[Financing Type] nvarchar(max), 
     [Gross Rent] nvarchar(max),[Hours of Operation] nvarchar(max), 
     [Lack of marketing] nvarchar(max),[Landlord Issues] nvarchar(max), 
     [Legal Entity] nvarchar(max),[Location Type] nvarchar(max), 
     [Market Type] nvarchar(max),[Median income > $50000] nvarchar(max), 
     [Members  Dues and PIF] nvarchar(max),[Monthly Fee Amt] nvarchar(max), 
     [Multi-Purpose Room] nvarchar(max),[Multi-Purpose Sq Ft] nvarchar(max), 
     [No Operating Capital] nvarchar(max),[No Sales Revenue] nvarchar(max), 
     [Number of Rooms] nvarchar(max),[Online Signup] nvarchar(max), 
     [Open Status] nvarchar(max),[Open Temporary Pending Relo] nvarchar(max), 
     [Opened On] nvarchar(max),[Original Franchisee Open Date] nvarchar(max), 
     [Other] nvarchar(max),[Other Equipment] nvarchar(max), 
     [Other Operating System] nvarchar(max),[Owner] nvarchar(max), 
     [Partnership Dispute] nvarchar(max),[Payroll] nvarchar(max), 
     [Percent Owner 1] nvarchar(max),[Percent Owner 2] nvarchar(max), 
     [Percent Owner 3] nvarchar(max),[Percent Owner 4] nvarchar(max), 
     [Percent Owner 5] nvarchar(max),[Percent Owner 6] nvarchar(max), 
     [Person  Training Revenue] nvarchar(max),[Personal Issues] nvarchar(max), 
     [Personal Training] nvarchar(max),[Personal Training Revenue] nvarchar(max) 
     ,[Primary Contact] nvarchar(max),[Principal Operator] nvarchar(max), 
     [Principal Owner] nvarchar(max),[Problem %] nvarchar(max), 
     [Profit Loss] nvarchar(max),[Remit Amount Last Quarter] nvarchar(max), 
     [Remit Amount Quarter Change] nvarchar(max),[Sale Date] nvarchar(max), 
     [Satellite Club] nvarchar(max),[Site] nvarchar(max),[Stage] nvarchar(max), 
     [Team Workouts] nvarchar(max),[Territory] nvarchar(max), 
     [Total Contracts] nvarchar(max),[Transfer Fee] nvarchar(max), 
     [Utilities] nvarchar(max),[Veteran] nvarchar(max), 
     [Virtual Coaching] nvarchar(max),[Waxing Account#] nvarchar(max), 
     [Website] nvarchar(max),[Active CMS] nvarchar(max), 
     [AFLP Auto Checklist] nvarchar(max),[AFLP In-club Training Lead] nvarchar(max), 
     [AFLP last Post-Launch Drip email sent] nvarchar(max), 
     [AFLP Marketing] nvarchar(max),[AFLP Notes] nvarchar(max), 
     [Agreement Renewal Date] nvarchar(max),[Agreement Signed] nvarchar(max), 
     [Average Contract Value] nvarchar(max),[Average Member Value] nvarchar(max) 
     ,[Billing Account Number] nvarchar(max),[BOE] nvarchar(max),[Brand] 
     nvarchar(max),[City] nvarchar(max),[Club OS] nvarchar(max), 
     [Club Ready] nvarchar(max),[Company] nvarchar(max),[Country] nvarchar(max), 
     [Created On] nvarchar(max),[Currency] nvarchar(max),[Draft %] nvarchar(max) 
     ,[Dues] nvarchar(max),[Exited Agreements] nvarchar(max), 
     [Latitude] nvarchar(max),[Location] nvarchar(max), 
     [Location #] nvarchar(max),[Longitude] nvarchar(max), 
     [Main Phone] nvarchar(max),[Modified On] nvarchar(max), 
     [Monthly Attrition] nvarchar(max),[NEW Agreements] nvarchar(max),[PIF %] 
     nvarchar(max),[Remit Amount] nvarchar(max),[Renewal Fee] nvarchar(max), 
     [Renewal Status] nvarchar(max),[Rolling 12 Month Attrition] nvarchar(max), 
     [Sq Ft] nvarchar(max),[State] nvarchar(max),[Status] nvarchar(max), 
     [Status Reason] nvarchar(max),[Time Zone] nvarchar(max), 
     [Total Rent] nvarchar(max),[Website URL] nvarchar(max), 
     [ZIP Postal Code] nvarchar(max),[AFLP Agreement] nvarchar(max), 
     [Current C2I] nvarchar(max),[Differentiator] nvarchar(max), 
     [Temporary Closure] nvarchar(max),[Closure Start Date] nvarchar(max), 
     [Closure End Date] nvarchar(max) 
  ) 